name: Build linux

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v0.4.2)'
        required: true
        default: 'v0.0.1'

jobs:
  build-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Node.js and npm
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          node -v
          npm -v

      - name: Install build tools
        run: |
          npm install --global electron-builder

      - name: Build
        run: |
          npm install
          npm run build:linux -- --publish=never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release with .AppImage
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: "pvzge Linux Release ${{ github.event.inputs.release_tag }}"
          body: "Automated Linux release built via GitHub Actions."
          files: release/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
