name: Build windows

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v0.4.2)'
        required: true
        default: 'v0.0.1'

jobs:
  build-electron:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Node.js and npm via Chocolatey
        run: |
          choco install -y nodejs-lts
          refreshenv
          node -v
          npm -v
        shell: pwsh

      - name: Install build tools
        run: |
          npm install --global electron-builder
        shell: pwsh

      - name: Build
        run: |
          npm install
          npm run build:win -- --publish=never
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release with portable .exe
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: "pvzge Windows Release ${{ github.event.inputs.release_tag }}"
          body: "Automated Windows release built via GitHub Actions."
          files: release\*.exe  # Matches only top-level .exe in release/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
